### ISSUE TITLE
lateinit property textInput has not been initialized

### ISSUE THREAD

**Issue by UdeeshaInduwara** [ligi/SurvivalManual#124]
After clone and run initially project.
It throw following exception. Need help ?

```
D/TraceDroid: Writing unhandled exception to: /data/user/0/org.ligi.survivalmanual/files/4.2.6-1598008368862.tracedroid
D/TraceDroid: kotlin.UninitializedPropertyAccessException: lateinit property textInput has not been initialized
        at org.ligi.survivalmanual.ui.MainActivity.access$getTextInput$p(MainActivity.kt:47)
        at org.ligi.survivalmanual.ui.MainActivity$$special$$inlined$observable$1.afterChange(Delegates.kt:76)
        at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
        at org.ligi.survivalmanual.ui.MainActivity.setInEditMode(MainActivity.kt)
        at org.ligi.survivalmanual.ui.MainActivity.access$setInEditMode$p(MainActivity.kt:47)
        at org.ligi.survivalmanual.ui.MainActivity$onCreate$2.run(MainActivity.kt:135)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.ligi.survivalmanual, PID: 28280
    kotlin.UninitializedPropertyAccessException: lateinit property textInput has not been initialized
        at org.ligi.survivalmanual.ui.MainActivity.access$getTextInput$p(MainActivity.kt:47)
        at org.ligi.survivalmanual.ui.MainActivity$$special$$inlined$observable$1.afterChange(Delegates.kt:76)
        at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
        at org.ligi.survivalmanual.ui.MainActivity.setInEditMode(MainActivity.kt)
        at org.ligi.survivalmanual.ui.MainActivity.access$setInEditMode$p(MainActivity.kt:47)
        at org.ligi.survivalmanual.ui.MainActivity$onCreate$2.run(MainActivity.kt:135)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by ligi** [comment]
It is important to get the content of the submodules - so you need to do
```
git submodules init
git submodules update
```

**Comment by pratikraman-dev** [comment]
git submodules init
git submodules update are not working 

git submodules init
git: 'submodules' is not a git command. See 'git --help'.

The most similar command is
        submodule

This Commands Work 👍 

git submodule init
git submodule update
