### ISSUE TITLE
Crash when long press on link

### ISSUE THREAD

**Issue by TNTima** [ligi/SurvivalManual#315]
# Description 
When pressing on link app crashes
#  Expected behaviour 
Opens share menu or nothing happens 
# Steps to replicate
1. Open app
2. Open menu (hamburger button)
3. Select "Apps"
4. Hold **Angulo** link
# Platform 
## Device 
Redmi 5 Plus
## MIUI version
MIUI Global 9.2
## Android version 
7.1.2
# Logs
___

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.Editor$SelectionModifierCursorController.getMinTouchOffset()' on a null object reference
	at android.widget.Editor.touchPositionIsInSelection(Editor.java:917)
	at android.widget.Editor.performLongClick(Editor.java:1018)
	at android.widget.TextView.performLongClick(TextView.java:9436)
	at android.view.View.performLongClick(View.java:5700)
	at android.view.View$CheckForLongPress.run(View.java:22431)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6363)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

**Comment by cowboydaniel** [comment]
Doesn't happen on Samsung S24 Ultra.
