### ISSUE TITLE
Issue in search

### ISSUE THREAD

**Issue by ligi** [ligi/SurvivalManual#61]
Steps to reproduce:
 * activate search in settings
 * go to poisonous plants in appendix
 * type p

Idea for solving it: don't search in the raw markdown - parse the markdown and only search in text nodes.

```
java.lang.RuntimeException: java.io.FileNotFoundException: md/image222.j<font%20color='red'>p</font>g
    at android.text.HtmlToSpannedConverter.convert(Html.java:448)
    at android.text.Html.fromHtml(Html.java:139)
    at org.ligi.compat.HtmlCompat.fromHtml(HtmlCompat.java:22)
    at org.ligi.survivalmanual.adapter.MarkdownRecyclerAdapter.setTextViewHTML(MarkdownRecyclerAdapter.kt:84)
    at org.ligi.survivalmanual.adapter.MarkdownRecyclerAdapter.setTextViewHTML$default(MarkdownRecyclerAdapter.kt:81)
    at org.ligi.survivalmanual.adapter.MarkdownRecyclerAdapter.onBindViewHolder(MarkdownRecyclerAdapter.kt:52)
    at org.ligi.survivalmanual.adapter.MarkdownRecyclerAdapter.onBindViewHolder(MarkdownRecyclerAdapter.kt:30)
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
    at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
    at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1618)
    at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4702)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
    at android.view.Choreographer.doCallbacks(Choreographer.java:613)
    at android.view.Choreographer.doFrame(Choreographer.java:582)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5653)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
    at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.io.FileNotFoundException: md/image222.j<font%20color='red'>p</font>g
    at android.content.res.AssetManager.openAsset(Native Method)
    at android.content.res.AssetManager.open(AssetManager.java:316)
    at android.content.res.AssetManager.open(AssetManager.java:290)
    at org.ligi.survivalmanual.adapter.MarkdownRecyclerAdapter$setTextViewHTML$CustomImageGetter.getDrawable(MarkdownRecyclerAdapter.kt:87)
    at android.text.HtmlToSpannedConverter.startImg(Html.java:637)
    at android.text.HtmlToSpannedConverter.handleStartTag(Html.java:523)
    at android.text.HtmlToSpannedConverter.startElement(Html.java:764)
    at org.ccil.cowan.tagsoup.Parser.push(Parser.java:794)
    at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1061)
    at org.ccil.cowan.tagsoup.Parser.stage(Parser.java:1026)
    at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:573)
    at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:449)
    at android.text.HtmlToSpannedConverter.convert(Html.java:445)
    at android.text.Html.fromHtml(Html.java:139) 
    at org.ligi.compat.HtmlCompat.fromHtml(HtmlCompat.java:22) 
    at org.ligi.survivalmanual.adapter.MarkdownRecyclerAdapter.setTextViewHTML(MarkdownRecyclerAdapter.kt:84) 
    at org.ligi.survivalmanual.adapter.MarkdownRecyclerAdapter.setTextViewHTML$default(MarkdownRecyclerAdapter.kt:81) 
    at org.ligi.survivalmanual.adapter.MarkdownRecyclerAdapter.onBindViewHolder(MarkdownRecyclerAdapter.kt:52) 
    at org.ligi.survivalmanual.adapter.MarkdownRecyclerAdapter.onBindViewHolder(MarkdownRecyclerAdapter.kt:30) 
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356) 
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389) 
    at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335) 
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598) 
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440) 
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436) 
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224) 
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551) 
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511) 
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595) 
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583) 
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312) 
    at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1618) 
    at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4702) 
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813) 
    at android.view.Choreographer.doCallbacks(Choreographer.java:613) 
    at android.view.Choreographer.doFrame(Choreographer.java:582) 
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799) 
    at android.os.Handler.handleCallback(Handler.java:733) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:146) 
    at android.app.ActivityThread.main(ActivityThread.java:5653) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:515) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
    at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by MystikHub** [comment]
I haven't been able to reproduce this issue and poisonous plants isn't even in the appendix any more. Is anyone else still having this problem?

**Comment by ligi** [comment]
yea I think this one can be closed
