### ISSUE TITLE
AssertionFailedError when running connectedAndroidTest

### ISSUE THREAD

**Issue by johnjohndoe** [ligi/SurvivalManual#81]
I tried to run a `connectedAndroidTest` task e.g. `connectedWithFirebaseForPlayDebugAndroidTest` on the [latest commit](https://github.com/ligi/SurvivalManual/commit/e0bf5d8b4fee674eacbd57156ec50a14110640aa) on the `master` branch. It fails with an `AssertionFailedError` which seems to be related to [TestButler](https://github.com/linkedin/test-butler). The error occurs when running the tests from the shell or from within Android Studio.
I tried with a Nexus 5, Android 6.0 and a Pixel 2, Android 9.

``` java
Testing started at 00:05 ...

09/20 00:05:01: Launching thatDayNightAutoIs...()
No apk changes detected since last installation, skipping installation of SurvivalManual/android/build/outputs/apk/SurvivalManual-4.2-withFirebase-forPlay-debug.apk
No apk changes detected since last installation, skipping installation of SurvivalManual/android/build/outputs/apk/SurvivalManual-4.2-withFirebase-forPlay-debug-androidTest.apk
Running tests

$ adb shell am instrument -w -r   -e debug false -e class 'org.ligi.survivalmanual.ThePreferenceActivity#thatDayNightAutoIsSelectable' org.ligi.survivalmanual.test/android.support.test.runner.AndroidJUnitRunner
Client not ready yet..
Started running tests

junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.linkedin.android.testbutler.AnimationAssertions.verifyAnimationsDisabled(AnimationAssertions.java:38)
at com.linkedin.android.testbutler.TestButler.verifyAnimationsDisabled(TestButler.java:155)
at org.ligi.trulesk.RulesKt.doBefore(Rules.kt:60)
at org.ligi.trulesk.RulesKt.access$doBefore(Rules.kt:1)
at org.ligi.trulesk.TruleskActivityRule.beforeActivityLaunched(Rules.kt:19)
at android.support.test.rule.ActivityTestRule.launchActivity(ActivityTestRule.java:329)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:431)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

Tests ran to completion.
```

I also tried to add the following [configuration option](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.TestOptions.html#com.android.build.gradle.internal.dsl.TestOptions:animationsDisabled) (which is also available in version 2.3 of the Android Plugin) to _android/build.gradle_ - without success, though.

``` groovy
android {
    testOptions {
        animationsDisabled = true
    }
}
```

**Comment by ligi** [comment]
you need to install test-butler on the device

**Comment by johnjohndoe** [comment]
Thanks for the clarification. I wasn't aware of this.
Does this mean that the connectedAndroidTests cannot be executed on a physical device?
